# ah
name: Ranik

# basic
verbose: true
silent: false

# input
data: ['items.csv']

# output
stub: items
overwrite: false
backup: true

# sql
hostname: localhost
database: dspdb
username: dspdb
password: dspdb
fail: true

# broker
restock: 3600
tick: 30

# scrub
itemids: []
stock01: 5
stock12: 5
urls: []
